export const BASE = 'f15d4eaba03d86786bec2de7aed1236718c813f9';
export const TASKS = {
 append: `Implement a new chainable Fastify reply.appendHeader(name, value) API in this existing Fastify v5.6.2 repository, not a plugin or new application.
Acceptance:
1. name is a valid HTTP header-name string; value is string|number|readonly (string|number)[]; reject invalid names, undefined/null/objects/nonfinite numbers and CR/LF or Node-invalid header values synchronously with TypeError BEFORE changing any header. Empty arrays are no-op but names still validate. Validate all array members before mutation.
2. Names are case-insensitive. Append without overwriting existing Fastify or raw Node response header values; Fastify values take precedence over raw when both exist (same as getHeader). Preserve order, duplicates and each value including empty string/zero. Normalize newly supplied numbers to strings; do not split strings on commas. Array output is acceptable for all nonempty operations. Copy caller arrays; do not mutate a raw/header array obtained before this operation.
3. set-cookie values append exactly once (do not duplicate old values through existing header special handling). Ordinary reply.header/headers behavior must remain unchanged.
4. Method returns this, works inside an encapsulated plugin and onSend, and values appear over real HTTP. Requests must not share mutable header state.
5. Declare correct chainable TypeScript types accepting readonly arrays and rejecting objects/undefined, document behavior with examples in docs/Reference/Reply.md, and add meaningful regression tests under test/. No new runtime dependency; do not delete/disable existing tests.
Consult the official Node HTTP reference supplied at /reference/node-http.md (frozen online source, URL/hash in /reference/provenance.json) and cite the relevant source in your final answer. Repository baseline command: node --test test/internals/reply.test.js test/internals/request.test.js. Dependencies already installed. Run relevant tests, typecheck where appropriate, and finish with concise change/test/limitation summary. Do not access evaluator files, other candidate runs or real credentials. Budget 900 seconds/120 tool calls; implement a small runnable patch early.`,
 vary: `Implement a new chainable Fastify reply.vary(fields) API in this existing Fastify v5.6.2 repository, not a plugin or new application.
Acceptance:
1. fields accepts a comma-separated string or readonly string[] (each element may itself contain commas). Trim optional ASCII space/tab around tokens; ignore empty tokens. Reject nonstrings, nested arrays and any nonempty invalid HTTP field-name token synchronously with TypeError BEFORE changing headers. CR/LF is invalid even at token edges; validate the whole input even if '*' is present. Empty input leaves the original header untouched.
2. Merge with the currently effective Vary header from Fastify or raw Node (Fastify precedence), supporting string/string[] existing values. Preserve first-seen spelling/order, deduplicate case-insensitively, and serialize using ', '. Existing duplicates must normalize on a nonempty call. '*' in existing/new values dominates and results in exactly '*'. No input array mutation.
3. Each call returns this, repeated calls accumulate, header casing does not matter, and other headers/reply.header semantics remain unchanged. Invalid calls leave both Fastify and raw header state unchanged.
4. Works in encapsulated plugin handlers and onSend; actual HTTP responses contain the merged Vary header. Independent requests must not share state.
5. Declare chainable TypeScript types accepting readonly string arrays and rejecting numbers/objects, document in docs/Reference/Reply.md with cache-negotiation example, and add meaningful regression tests under test/. No new runtime dependency; do not delete/disable existing tests.
Consult the supplied official HTTP Vary reference at /reference/rfc9110.txt (frozen online source, URL/hash in /reference/provenance.json) and cite it in the final answer. Repository baseline command: node --test test/internals/reply.test.js test/internals/request.test.js. Dependencies already installed. Run relevant tests and typechecks and finish with concise change/test/limitation summary. Do not access evaluator files, other candidate runs or real credentials. Budget 900 seconds/120 tool calls; implement a small runnable patch early.`
};
export const MATRIX = [['append','plain'],['append','harness'],['append','jev'],['vary','jev'],['vary','harness'],['vary','plain']];
