/** Rotating completion lines for the TUI banner — one is drawn at random when a
 * run settles. Carthage-themed to match the Aleph mark. */

export const CARTHAGE_LINES = [
  'Qart-Hadasht endures',
  'The cothon is calm',
  'The fleet is in',
  'Byrsa stands watch',
  'Purple on the tide',
  'Cedar holds fast',
  'Hannibal approves',
  'The harbormaster nods',
  "Elissa's city rises",
  'Tanit smiles',
  'The galleys rest',
  'Salt and cedar',
  'The Barca line holds',
  'Silver from Tartessos',
  'The suffetes concur',
  'New City, new win',
  'The murex trade thrives',
  'Utica sends regards',
  'Across the Middle Sea',
  'The seawall stands',
  'Hanno sails on',
  'Elephants crossed the Alps',
  'The Alps are behind you',
  'Cannae was harder',
  'The quinqueremes row on',
  "Melqart's favor is yours",
  'The Punic ports are open',
  'A stele raised in your honor',
  'The Gulf of Tunis glitters',
  'The tin routes run',
  'Motya sends tribute',
  'Sardinia remembers',
  'The Hundred and Four approve',
  'Hamilcar would grin',
  "Hasdrubal's blessing",
  'The agora buzzes',
  'The breakwater holds',
  'The Punic tide runs your way',
  "Dido's dream endures",
  'Carthago Nova salutes',
  "The admiral's lantern is lit",
  'Trade winds at your back',
  'The merchant fleet prospers',
  'The citadel is yours',
  'Purple sails unfurled',
  "Mago's harvest is in",
  'The vineyards of the Bagradas',
  'Olive presses run full',
  'The last amphora is sealed',
  'The mint strikes silver',
  "Tanit's sign on the coin",
  'The mare and the palm',
  'Beyond the Pillars of Hercules',
  'Gadir holds the strait',
  'Numidian riders rest',
  'Baal Hammon is pleased',
  'Libyan wheat loads fast',
  'The customs house is quiet',
  "Delivered under Byrsa's shadow",
  'The Phoenician star guides you',
  'Charted to the edge of maps',
  'Landfall, finally',
  'Anchored in calm water',
  'Cargo counted, cargo safe',
  'The manifest is clean',
  'Every bale stamped',
  'Sealed and shipped',
  'The ledger balances',
  'Harbor dues paid',
  'The convoy made it',
  'Full cargo, calm seas',
  'The emporium is stocked',
  'The tide is with us',
  'Sunset over the great harbor',
  'The sea gate closes softly',
  'The watch changes',
  'Carthage remembers',
  'The oxhide was worth it',
  'Byrsa, measured in oxhide',
  'The circle of the cothon',
  'Two hundred oars, one rhythm',
  'The arsenal is full',
  'Pitch and pine',
  'Rope of esparto',
  'The lookout calls landfall',
  'Where the gulf meets the wall',
  'Sea-borne and sure',
  'The Punic way prevails',
  "Tyre's daughter prospers",
  'Ivory and gold dust',
  'Amber from the north',
  'Crimson dye for the victor',
  'The archive keeps your name',
  "Eshmun's blessing",
  'Wax tablets sealed',
  'The drum calls the stroke',
  'Dawn patrol returns',
  'Cap Bon rises green',
  'The Lake of Tunis at dusk',
  'The prow cuts true',
];

export function pickCarthageLine() {
  return CARTHAGE_LINES[Math.floor(Math.random() * CARTHAGE_LINES.length)];
}
